BookStore.WebUI/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Domain.Abstract;
using BookStore.WebUI.Models;
using BookStore.Domain.Entities;

namespace BookStore.WebUI.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        private IBookRepository repository;
        public int pageSize = 3;
        
        public BookController(IBookRepository bookRep)
        {
            repository = bookRep;
        }

        public ViewResult List(string specialization,int pageno=1)
        {
            BookListViewModel model = new BookListViewModel
            {
                Books = repository.Books
                       .Where(b=>specialization==null||b.Specialization==specialization)
                       .OrderBy(b => b.ISBN)
                       .Skip((pageno - 1) * pageSize)
                       .Take(pageSize),
                paginginfo = new PageingInfo
                {
                    CurrentPage=pageno,
                    ItemPerPage=pageSize,
                    TotalItems=specialization==null? repository.Books.Count():
                    repository.Books.Where(b => b.Specialization == specialization).Count()
                },
                CurrentSpecialization=specialization
            };

            return View(model);

        }


        public FileContentResult GetImage(int ISBN)
        {
            Book book = repository.Books
                       .FirstOrDefault(b =>b.ISBN == ISBN);
            if (book != null)
            {
                return File(book.ImageData, book.ImageMimeType);
            }
            else
                return null;
        }
        //public ViewResult ListAll()
        //{
        //    return View(repository.Books);
        //}
    }
}

BookStore.WebUI/Controllers/CartController.cs
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using BookStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IBookRepository repo,IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }
        public RedirectToRouteResult AddToCart(Cart cart,int isbn, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(b=>b.ISBN==isbn);
            if(book!=null)
            {
                cart.AddItem(book);
            }
            return RedirectToAction("Index", new { returnUrl});
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart,int isbn, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(b => b.ISBN == isbn);
            if (book != null)
            {
                cart.RemoveLine(book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

       

        public ViewResult Index(Cart cart,string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart=cart,
                ReturnUrl=returnUrl
            }
                
                       );
        }


        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View (new ShippingDetails());
        }



        [HttpPost]//because Cart and ShippingDetails Depends on Session From Http
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
                ModelState.AddModelError("","Sorry,Your Cart is empty");
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
                return View(shippingDetails);
                
        }
    }
}

BookStore.WebUI/Controllers/NavController.cs
using BookStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repository;
        public NavController(IBookRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string specialization=null,bool mobileLayout = false)
        {
          ViewBag.SelectedSpec = specialization;
            IEnumerable<string> spec = repository.Books
                 .Select(b => b.Specialization)
                 .Distinct();


            string ViewName = mobileLayout ? "MenuHorizontal" : "Menu";
           
            return PartialView(ViewName,spec); 
        }
    }
}

BookStore.WebUI/Views/Shared/BookSummary.cshtml
@model BookStore.Domain.Entities.Book

<style>
    #aa {
        height:130px;
    }
</style>
<div class="well" id="aa" >

    @if (Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right:10px">
            <img class="img-circle" width="100" height="100"
                 src="@Url.Action("GetImage","Book",new { Model.ISBN})" />
        </div>

    }
    <h3>
        <strong>@Model.Title</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>

    @using (Html.BeginForm("AddToCart", "Cart"))
    {
    <div class="pull-right">
        @Html.HiddenFor(b => b.ISBN)
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
        <input type="submit" class="btn btn-success" value="Add to Cart">
    </div>
    }
</div>

BookStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet"/>
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />
    <script src="~/scripts/jquery-1.10.2.js"></script>
    <script src="~/scripts/jquery.validate.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

BookStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" media="screen" href="your-app-core.css">
    <link rel="stylesheet" type="text/css" media="print" href="your-app-core-print.css">

    <style>
        .navbar-right{float:right !important;
                      margin-right:15px;
                      margin-left:15px;
        }
    </style>
</head>
<body>
    
    <div class="navbar navbar-inverse" role="navigation">
       
        <input type="button" value="Print Document" onclick="window.print()" class="btn btn-primary" />
        
        <a class="navbar-brand" href="#">
        <style class="hidden-xs">Book Store</style>
            <div class="visible-xs"> Book</div>
            <div class="visible-xs">Store </div>
        </a>
        @Html.Action("Summary", "Cart");
    </div>

    <div class="visible-xs">
        @Html.Action("Menu","Nav",new { mobileLayout=true})
    </div>
    <div class="row panel">
        <div id="specialization" class="col-xs-3 hidden-xs" >
            @Html.Action("Menu", "Nav");
         </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()

        </div>
     </div>
    

    
</body>
</html>