BookStore.WebUI/Controllers/AdminController.cs
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    public class AdminController : Controller
    {

        // GET: Admin
       
        private IBookRepository repository;
        public AdminController(IBookRepository repo)
        {
            repository = repo;
        }

      
        public ViewResult Index()
        {
            
            return View(repository.Books);
        }
        [HttpPost]
        public ViewResult Index(string searchValue)
        {
            IEnumerable<Book> books;
            books = from b in repository.Books
                    where b.Description.IndexOf(searchValue) >= 0 ||
                          b.Title.IndexOf(searchValue) >= 0 ||
                          b.Specialization.IndexOf(searchValue) >= 0
                    select b;
            return View("Index",books);
        }

        public ViewResult Edit(int isbn)
        {
            Book book = repository.Books.FirstOrDefault(b=>b.ISBN==isbn);
            return View(book);
        }

        [HttpPost]
        public ActionResult Edit(Book book, HttpPostedFileWrapper image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    book.ImageMimeType = image.ContentType;
                    book.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(book.ImageData, 0, image.ContentLength);
                }
                repository.SaveBook(book);
                TempData["message"] = book.Title + " has been Saved";
                return RedirectToAction("Index");
            }
            else
            {
                //Not Completed

                return View(book);
            }
        }



        public ActionResult Create()
        {
            return View ("Edit",new Book());
        }

        public ActionResult Delete(int ISBN)
        {
            Book deleteBook = repository.Delete(ISBN);
            if (deleteBook != null)
            {
                TempData["message"] = deleteBook.Title + "has been Deleted";
            }
            return RedirectToAction("Index");
        }
    }
}

BookStore.WebUI/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Domain.Abstract;
using BookStore.WebUI.Models;
using BookStore.Domain.Entities;

namespace BookStore.WebUI.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        private IBookRepository repository;
        public int pageSize = 3;
        
        public BookController(IBookRepository bookRep)
        {
            repository = bookRep;
        }

        public ViewResult List(string specialization,int pageno=1)
        {
            BookListViewModel model = new BookListViewModel
            {
                Books = repository.Books
                       .Where(b=>specialization==null||b.Specialization==specialization)
                       .OrderBy(b => b.ISBN)
                       .Skip((pageno - 1) * pageSize)
                       .Take(pageSize),
                paginginfo = new PageingInfo
                {
                    CurrentPage=pageno,
                    ItemPerPage=pageSize,
                    TotalItems=specialization==null? repository.Books.Count():
                    repository.Books.Where(b => b.Specialization == specialization).Count()
                },
                CurrentSpecialization=specialization
            };

            return View(model);

        }


        public FileContentResult GetImage(int ISBN)
        {
            Book book = repository.Books
                       .FirstOrDefault(b =>b.ISBN == ISBN);
            if (book != null)
            {
                return File(book.ImageData, book.ImageMimeType);
            }
            else
                return null;
        }
        //public ViewResult ListAll()
        //{
        //    return View(repository.Books);
        //}
    }
}

BookStore.WebUI/Views/Admin/Edit.cshtml
@model BookStore.Domain.Entities.Book

@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    HtmlHelper.ClientValidationEnabled = false;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
}

<div class="panel">
    <div class="panel-heading">
        <h2>Edit Book:@Model.Title</h2>
    </div>

    @using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(b => b.ISBN)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "ISBN" &&
                    property.PropertyName != "ImageData" &&
                    property.PropertyName != "ImageMimeType")
                {
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description")
                        { @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })}
                        else
                        {
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                        }
                        @Html.ValidationMessage(property.PropertyName)
                    </div>
                }
            }
        </div>

        <div class="form-group">
            <div style="position:relative">
                <label>Image:</label>
                <a class="btn" href="javascript:;">
                    Choose Image...
                    <input type="file" name="image" size="40" id="image" style="position:absolute;
                              top:8;left:10;
                              opacity:30; background-color:transparent; color:transparent"
                           onchange='$("upload-file-info").html($(this).val())' />
                </a>
                <span class="label label-info" id="upload-file-info"></span>
            </div>
            @if (Model.ImageData == null)
            { <div class="form-control-static">No Image</div>}
            else
            {
                <img class="img-circle" width="150" height="150" src="@Url.Action("GetImage","Book",new { Model.ISBN})" />
            }
        </div>
        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List","Index",null,new { @class = "btn btn-default" })
        </div>

    }
</div>

BookStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<BookStore.Domain.Entities.Book>

@{
    ViewBag.Title = "Index:All Books";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Book Index</h2>


<div class="panel panel-default">
    <div class="panel-heading" style="height:100px;">
        <h3>All Books</h3>
        <div class="text-right form-group" style="margin-top:-30px">
            <form action="Index" method="post">
                <input id="searchValue" name="searchValue" type="Search" placeholder="Search For Books" />
                <input type="submit" value="Search" class="btn btn-info" />
            </form>
        </div> 
    </div>
    <div class="panel-body">


        <table class="table table-condensed table-striped table-bordered">
            <tr>
                <th class="text-right">
                    ID
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Specialization)
                </th>
                <th>
                    Action
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.ISBN)
                    </td>
                    <td >
                        @Html.ActionLink(item.Title, "Edit",new {item.ISBN })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td class="text-right">
                        @item.Price.ToString("c")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Specialization)
                    </td>
                    <td class="text-center">
                        @Html.ActionLink("Delete", "Delete", new {item.ISBN },new { @class="btn btn-danger btn-xs"})
                    </td>
                </tr>
            }

        </table>

    </div>

    <div class="panel-footer">
        @Html.ActionLink("Add New Book", "Create",null,new { @class="btn btn-default"})
    </div>
</div> 